export default function TermsOfUse() {
  return (
    <main style={{ maxWidth: 800, margin: "0 auto", padding: "40px 24px", fontFamily: "system-ui, sans-serif", color: "#111827", lineHeight: 1.7 }}>
      <h1 style={{ fontSize: 32, fontWeight: 800, marginBottom: 8 }}>Terms of Use</h1>
      <p style={{ color: "#6b7280", marginBottom: 32 }}>Last updated: June 21, 2026</p>

      <p>These Terms of Use ("Terms") govern your use of the NutriMap AI mobile application and website (nutrimapai.vercel.app) operated by NutriMap AI ("we", "our", or "us"). By using the Service, you agree to these Terms.</p>

      <h2 style={{ fontSize: 22, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>Subscriptions</h2>
      <p>NutriMap AI offers auto-renewable subscriptions for premium features:</p>
      <ul>
        <li><strong>NutriMap AI Premium (Monthly)</strong> — $7.99 per month</li>
        <li><strong>NutriMap AI Premium (Annual)</strong> — billed annually</li>
      </ul>
      <p>Payment will be charged to your Apple ID account at confirmation of purchase. Subscriptions automatically renew unless auto-renew is turned off at least 24 hours before the end of the current period. Your account will be charged for renewal within 24 hours prior to the end of the current period. You can manage and cancel your subscriptions by going to your account settings in the App Store after purchase. Any unused portion of a free trial period, if offered, will be forfeited when you purchase a subscription.</p>

      <h2 style={{ fontSize: 22, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>Use of the Service</h2>
      <p>You agree to use the Service only for lawful purposes. You must be at least 13 years old to use NutriMap AI. You are responsible for maintaining the confidentiality of your account credentials.</p>

      <h2 style={{ fontSize: 22, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>Not Medical Advice</h2>
      <p>NutriMap AI provides AI-generated meal plans and nutrition information for general informational purposes only. It is not a medical service and does not provide medical, dietary, or health advice. Always consult a qualified healthcare professional before making changes to your diet, especially if you have a medical condition, allergy, or are pregnant. You use the Service and any recommendations at your own risk.</p>

      <h2 style={{ fontSize: 22, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>AI-Generated Content</h2>
      <p>Meal plans and nutrition recommendations are generated using Claude AI (by Anthropic). AI-generated content may contain inaccuracies. We do not guarantee the accuracy, completeness, or suitability of any nutrition information or meal plan generated by the Service.</p>

      <h2 style={{ fontSize: 22, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>Intellectual Property</h2>
      <p>The Service and its original content, features, and functionality are owned by NutriMap AI and are protected by copyright and other intellectual property laws. You may not copy, modify, distribute, or reverse-engineer any part of the Service.</p>

      <h2 style={{ fontSize: 22, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>Limitation of Liability</h2>
      <p>To the maximum extent permitted by law, NutriMap AI shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of, or inability to use, the Service. The Service is provided "as is" without warranties of any kind.</p>

      <h2 style={{ fontSize: 22, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>Termination</h2>
      <p>We may suspend or terminate your access to the Service at any time, without notice, for conduct that violates these Terms or is harmful to other users or to us.</p>

      <h2 style={{ fontSize: 22, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>Changes to These Terms</h2>
      <p>We may update these Terms from time to time. We will notify you of any changes by posting the new Terms on this page. Your continued use of the Service after changes are posted constitutes acceptance of the revised Terms.</p>

      <h2 style={{ fontSize: 22, fontWeight: 700, marginTop: 32, marginBottom: 12 }}>Contact Us</h2>
      <p>If you have questions about these Terms, contact us at: <a href="mailto:sthayes.0622@gmail.com" style={{ color: "#16a34a" }}>sthayes.0622@gmail.com</a></p>
    </main>
  );
}
